web:
  restart: always
  build: ./django
  expose:
    - "8000"
  links:
    - postgres:postgres
  volumes:
    - ../backEnd:/webapp/backEnd
    - ../frontEnd/build:/webapp/frontEnd
    - ../logs:/webapp/logs
    - ../robots:/webapp/robots
  env_file: ./.env
  command: /rundjango.sh

front-end:
  build: ./front-end
  volumes:
    - ../frontEnd:/webapp/frontEnd
    - /webapp/frontEnd/node_modules
  command: npm run-script build

nginx:
  restart: always
  build: ./nginx/
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - certs:/etc/letsencrypt
    - certs-data:/data/letsencrypt
  volumes_from:
    - web
  links:
    - web:web

postgres:
  restart: always
  env_file: ./.env
  build: ./postgres
  ports:
    - "5433:5432" #expose port 5432
  volumes:
    - postgres-data:/var/lib/postgresql/data
