web:
  restart: always
  build: ./django
  expose:
    - "8000"
  links:
    - postgres:postgres
  volumes:
    - ../backEnd:/webapp/backEnd
    - ../frontEnd/build:/webapp/frontEnd
    - ../logs:/webapp/logs
    - ../robots:/webapp/robots
  env_file: ./.env
  command: /rundjango.sh

nginx:
  restart: always
  build: ./nginx/
  ports:
    - "80:80"
  volumes_from:
    - web
  links:
    - web:web

postgres:
  restart: always
  env_file: ./.env
  build: ./postgres
  ports:
    - "5433:5432" #expose port 5432
  volumes:
    - postgres-data:/var/lib/postgresql/data
